version: "3.8"
services:
  db:
    image: mariadb:10.11
    container_name: cafeteria-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: admin_app_cafeteria
      MYSQL_USER: admin_administrador
      MYSQL_PASSWORD: Admin_cafeteria2024
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./localhost.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - cafeteria-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
    networks:
      - cafeteria-network

networks:
  cafeteria-network:

  
